### ISSUE TITLE
the version of numpy did not work

### ISSUE THREAD

**Issue by abakane1** [mganjoo/apple-health-exporter#1]
when I use the numpy-1.12.0, there is a problem shows that

> RuntimeError: module compiled against API version 0xc but this version of numpy is 0xa

I try 

> pip uninstall numpy
and 

> pip install numpy 

the numpy-1.14.0 worked

ps python 3.5

**Comment by mganjoo** [comment]
Just upgraded the versions of packages in `requirements.txt`, so this should be resolved.
